services:
  - type: web
    name: frontend
    buildCommand: "npm install && npm install --prefix Frontend && npm run build --prefix Frontend"
    startCommand: "NODE_ENV=production node Backend/server.js"
    env:
      - key: NODE_ENV
        value: "production"
    git:
      branch: main
      repo: https://github.com/devpaurakh/Bookstore.git
